[run]
init_cmds = [
  ["make", "update-workspace"],
  ["make", "GO_BUILD_DEV=1", "build-backend"],
  ["make", "gen-jsonnet"],
  ["./bin/grafana", "server", "-profile", "-profile-addr=127.0.0.1", "-profile-port=6000", "-profile-block-rate=1", "-profile-mutex-rate=5", "-packaging=dev", "cfg:app_mode=development"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [
  "$WORKDIR/apps",
  "$WORKDIR/pkg",
  "$WORKDIR/public/views",
  "$WORKDIR/conf",
  "$WORKDIR/devenv/dev-dashboards",
]
watch_exts = [".go", ".ini", ".toml", ".template.html"]
ignore_files = [".*_gen.go", ".*_test.go", "pkg/extensions/ext.go"]
build_delay = 10000
cmds = [
  ["sleep", "1"],
  ["make", "gen-go"],
  ["make", "GO_BUILD_DEV=1", "build-backend"],
  ["make", "gen-jsonnet"],
  ["./bin/grafana", "server", "-profile", "-profile-addr=127.0.0.1", "-profile-port=6000", "-profile-block-rate=1", "-profile-mutex-rate=5", "-packaging=dev", "cfg:app_mode=development"]
]
