//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaFoo = resource.NewSimpleSchema("foobar.ext.grafana.com", "v1", &Foo{}, &FooList{}, resource.WithKind("Foo"),
		resource.WithPlural("foos"), resource.WithScope(resource.ClusterScope))
	kindFoo = resource.Kind{
		Schema: schemaFoo,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &FooJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func FooKind() resource.Kind {
	return kindFoo
}

// Schema returns a resource.SimpleSchema representation of Foo
func FooSchema() *resource.SimpleSchema {
	return schemaFoo
}

// Interface compliance checks
var _ resource.Schema = kindFoo
