name: Reusable Crowdin Upload Workflow

on:
  workflow_call:
    inputs:
      crowdin_project_id:
        description: 'The Crowdin project ID'
        required: true
        type: number
      crowdin_config:
        description: 'The location of the crowdin.yml file'
        required: false
        type: string
        default: 'crowdin.yml'

jobs:
  upload-sources-to-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # needed to get vault secrets

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Get vault secrets"
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main # zizmor: ignore[unpinned-uses]
        with:
          # Vault secret paths:
          # - ci/repo/grafana/grafana/grafana_frontend_platform_crowdin_bot
          repo_secrets: |
            CROWDIN_TOKEN=grafana_frontend_platform_crowdin_bot:access_token

      - name: Upload sources
        uses: crowdin/github-action@b8012bd5491b8aa8578b73ab5b5f5e7c94aaa6e2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          create_pull_request: false
          base_url: 'https://grafana.api.crowdin.com'
          config: ${{ inputs.crowdin_config }}
        env:
          CROWDIN_PROJECT_ID: ${{ inputs.crowdin_project_id }}
          CROWDIN_PERSONAL_TOKEN: ${{ env.CROWDIN_TOKEN }}
