name: Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    paths:
      - 'public/locales/en-US/grafana.json'
      - 'public/app/plugins/datasource/azuremonitor/locales/en-US/grafana-azure-monitor-datasource.json'
    branches:
      - main

jobs:
  upload-sources-to-crowdin:
    uses: ./.github/workflows/crowdin-upload.yml
    with:
      crowdin_project_id: 5
