name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download-sources-from-crowdin:
    uses: ./.github/workflows/crowdin-download.yml
    with:
      crowdin_project_id: 5
      pr_labels: 'area/frontend, area/internationalization, no-changelog, no-backport'
      project_id: 78

  auto-milestone-and-approve:
    runs-on: ubuntu-latest
    needs: download-sources-from-crowdin
    if: ${{ needs.download-sources-from-crowdin.outputs.pull_request_url != '' }}
    steps:
      - name: Get vault secrets
        id: vault-secrets-approver
        uses: grafana/shared-workflows/actions/get-vault-secrets@main # zizmor: ignore[unpinned-uses]
        with:
          # Secrets placed in ci/repo/grafana/grafana/grafana-pr-approver
          repo_secrets: |
            GRAFANA_PR_APPROVER_APP_ID=grafana-pr-approver:app-id
            GRAFANA_PR_APPROVER_APP_PEM=grafana-pr-approver:private-key

      - name: Generate approver token
        id: generate_approver_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ env.GRAFANA_PR_APPROVER_APP_ID }}
          private_key: ${{ env.GRAFANA_PR_APPROVER_APP_PEM }}

      - name: Run auto-milestone
        uses: grafana/grafana-github-actions-go/auto-milestone@main # zizmor: ignore[unpinned-uses]
        with:
          pr: ${{ needs.download-sources-from-crowdin.outputs.pull_request_number }}
          token: ${{ steps.generate_approver_token.outputs.token }}

      - name: Approve and automerge PR
        shell: bash
        # Only approve if:
        # - the PR does not modify files other than json files under the public/locales/ directory
        # - the PR does not modify the en-US locale
        # TODO make these paths inputs to the workflow when we move this to a shared repo
        run: |
          filesChanged="$(gh pr diff --name-only ${{ needs.download-sources-from-crowdin.outputs.pull_request_url }})"

          if [[ $(echo "$filesChanged" | grep -cv -e 'public/locales/[a-zA-Z\-]*/grafana.json' -e 'public/app/plugins/datasource/azuremonitor/locales/[a-zA-Z\-]*/grafana-azure-monitor-datasource.json') -ne 0 ]]; then
            echo "Non-i18n changes detected, not approving"
            exit 1
          fi

          if [[ $(echo "$filesChanged" | grep -c -e "public/locales/en-US" -e "public/app/plugins/datasource/azuremonitor/locales/en-US") -ne 0 ]]; then
            echo "en-US changes detected, not approving"
            exit 1
          fi

          echo "Approving and enabling automerge"
          gh pr review ${{ needs.download-sources-from-crowdin.outputs.pull_request_url }} --approve
          gh pr merge --auto --squash ${{ needs.download-sources-from-crowdin.outputs.pull_request_url }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_approver_token.outputs.token }}
