name: Reproduce push error backport
on:
  push:
    branches:
    - joshhunt/debug-backport-action

permissions: {}

jobs:
  push-and-pr:
    if: github.repository == 'grafana/grafana'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Get vault secrets
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          # Secrets placed in the ci/data/repo/grafana/grafana/delivery-bot-app path in Vault
          repo_secrets: |
            GRAFANA_DELIVERY_BOT_APP_PEM=delivery-bot-app:PRIVATE_KEY
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ vars.DELIVERY_BOT_APP_ID }}
          private_key: ${{ env.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: Checkout Grafana
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 2
          fetch-tags: false
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: true
      - name: Configure git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local --add --bool push.autoSetupRemote true
      - name: Create backport branch
        run: |
          git fetch --depth=2 origin release-11.2.10
          git switch --create backport-${{ github.run_id }}-to-release-11.2.10 origin/release-11.2.10
      - name: Pretend to cherry-pick
        run: |
          touch new-file.txt
          git add new-file.txt
          git commit --allow-empty -m "Add new file (testing)"
      - name: Git push
        run: |
          git status
          git branch -vv
          git remote -v
          git log -n 5 --oneline
          GIT_TRACE2=1 GIT_CURL_VERBOSE=1 git push --set-upstream origin backport-${{ github.run_id }}-to-release-11.2.10
      - name: Create PR without backports
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            -l "no-changelog" \
            -B "backport-${{ github.run_id }}-to-release-11.2.10" \
            --dry-run=true \
            --base "release-11.2.10" \
            --title "[Testing (@joshhunt)] Testing automation push error" \
            --body "Ignore this, testing pushes from automation for support ticket because of all of the backport.yml failures"
