name: Send Slack Notification

on:
  workflow_run:
   workflows:
     - Integration Tests
     - Backend Unit Tests
   types:
     - completed

jobs:
  notify:
    if: >
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "It worked!"
