name: Integration Tests Next Major Release

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NEXT_MAJOR_RELEASE_FEATURE_TOGGLES: kubernetesClientDashboardsFolders,kubernetesDashboards

jobs:
  sqlite:
    name: Sqlite with Next Major Release config
    runs-on: ubuntu-latest-8-cores
    env:
      GF_FEATURE_TOGGLES_ENABLE: ${{ env.NEXT_MAJOR_RELEASE_FEATURE_TOGGLES }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Restore GOCACHE
        uses: actions/cache/restore@v4
        with:
          key: go-test-cache-${{ github.ref_name }}-sqlite-next-major-release
          restore-keys: |
            go-test-cache-${{ github.base_ref }}-sqlite-next-major-release
            go-test-cache-main-sqlite-next-major-release
          path: /home/runner/.cache/go-build
      - run: |
          make gen-go
          go test -tags=sqlite -timeout=5m -run '^TestIntegration' $(find ./pkg -type f -name '*_test.go' -exec grep -l '^func TestIntegration' '{}' '+' | grep -o '\(.*\)/' | sort -u)
      - name: Save GOCACHE
        uses: actions/cache/save@v4
        with:
          key: go-test-cache-${{ github.ref_name }}-sqlite-next-major-release
          path: /home/runner/.cache/go-build
  mysql:
    name: MySQL with Next Major Release config
    runs-on: ubuntu-latest-8-cores
    env:
      GRAFANA_TEST_DB: mysql
      MYSQL_HOST: 127.0.0.1
      GF_FEATURE_TOGGLES_ENABLE: ${{ env.NEXT_MAJOR_RELEASE_FEATURE_TOGGLES }}
    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: grafana_tests
          MYSQL_USER: grafana
          MYSQL_PASSWORD: password
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Restore GOCACHE
        uses: actions/cache/restore@v4
        with:
          key: go-test-cache-${{ github.ref_name }}-mysql-next-major-release
          restore-keys: |
            go-test-cache-${{ github.base_ref }}-mysql-next-major-release
            go-test-cache-main-mysql-next-major-release
          path: /home/runner/.cache/go-build
      - run: |
          sudo apt-get update -yq && sudo apt-get install mariadb-client
          cat devenv/docker/blocks/mysql_tests/setup.sql | mariadb -h 127.0.0.1 -P 3306 -u root -prootpass --disable-ssl-verify-server-cert
          make gen-go
          go test -tags=mysql -p=1 -timeout=5m -run '^TestIntegration' $(find ./pkg -type f -name '*_test.go' -exec grep -l '^func TestIntegration' '{}' '+' | grep -o '\(.*\)/' | sort -u)
      - name: Save GOCACHE
        uses: actions/cache/save@v4
        with:
          key: go-test-cache-${{ github.ref_name }}-mysql-next-major-release
          path: /home/runner/.cache/go-build
  postgres:
    name: Postgres with Next Major Release config
    runs-on: ubuntu-latest-8-cores
    env:
      GRAFANA_TEST_DB: postgres
      PGPASSWORD: grafanatest
      POSTGRES_HOST: 127.0.0.1
      GF_FEATURE_TOGGLES_ENABLE: ${{ env.NEXT_MAJOR_RELEASE_FEATURE_TOGGLES }}
    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: grafanatest
          POSTGRES_PASSWORD: grafanatest
          POSTGRES_DB: grafanatest
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Restore GOCACHE
        uses: actions/cache/restore@v4
        with:
          key: go-test-cache-${{ github.ref_name }}-postgres-next-major-release
          restore-keys: |
            go-test-cache-${{ github.base_ref }}-postgres-next-major-release
            go-test-cache-main-postgres-next-major-release
          path: /home/runner/.cache/go-build
      - run: |
          sudo apt-get update -yq && sudo apt-get install postgresql-client
          psql -p 5432 -h 127.0.0.1 -U grafanatest -d grafanatest -f devenv/docker/blocks/postgres_tests/setup.sql
          make gen-go
          go test -p=1 -tags=postgres -timeout=5m -run '^TestIntegration' $(find ./pkg -type f -name '*_test.go' -exec grep -l '^func TestIntegration' '{}' '+' | grep -o '\(.*\)/' | sort -u)
      - name: Save GOCACHE
        uses: actions/cache/save@v4
        with:
          key: go-test-cache-${{ github.ref_name }}-postgres-next-major-release
          path: /home/runner/.cache/go-build
