name: syft-sbom-ci
on:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  syft-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Anchore SBOM Action
      uses: grafana/shared-workflows/actions/syft-sbom-report/syft-sbom-report.yml@main
      with:
        artifact-name: ${{ github.event.repository.name }}-spdx.json
